services:
  openssl-init:
    image: ${OPEN_SSL_IMAGE}:${OPEN_SSL_TAG}
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        if [ ! -f /jwt/jwt.hex ]; then
          echo 'Generating jwt secret'
          openssl rand -hex 32 | tr -d '\n' > /jwt/jwt.hex
        else
          echo 'JWT secret already exists'
        fi
        if [ ! -f /consensus/ec-secp256k1-non-validator.pem ]; then
          echo 'Generating secp256k1 keypair for non-validator'
          openssl ecparam -name secp256k1 -genkey -noout -out /consensus/ec-secp256k1-non-validator.pem
          openssl ec -in /consensus/ec-secp256k1-non-validator.pem -outform DER -no_public -out /consensus/ec-secp256k1-non-validator.der
        else
          echo 'secp256k1 keypair for non-validator already exists'
        fi
        echo 'OpenSSL initialization completed'
    user: "1000:1000"
    env_file: .env
    container_name: openssl-init
    volumes:
      - ${DATA_DIR}/consensus:/consensus:rw
      - ${DATA_DIR}/jwt:/jwt:rw

  init-consensus:
    image: ${PLASMA_CONSENSUS_IMAGE}:${PLASMA_CONSENSUS_TAG}
    user: "1000:1000"
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        if [ ! -f /consensus/data.mdb ]; then
          echo "Generating consensus database for $NETWORK network"
          plasma-cli init \
            --chain /node/$NETWORK.json \
            --data-dir /consensus
        else
          echo "Consensus database for $NETWORK network already exists"
        fi

        if [ ! -f /config/peer-id.txt ]; then
          echo "Generating peer ID for non-validator"
          plasma-cli peer-id \
            --identity-file-path /consensus/ec-secp256k1-non-validator.der > /config/peer-id.txt
        else
          echo "Peer ID for non-validator already exists"
        fi
    env_file: .env
    volumes:
      - ${DATA_DIR}/consensus:/consensus:rw
      - ${DATA_DIR}/genesis:/config:rw
      - ./shared/${NETWORK}.json:/node/${NETWORK}.json:ro
    depends_on:
      openssl-init:
        condition: service_completed_successfully

  init-execution:
    image: ${PLASMA_EXECUTION_IMAGE}:${PLASMA_EXECUTION_TAG}
    user: "1000:1000"
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        if [ ! -f /execution/db/mdbx.dat ]; then
          echo "Generating execution database for $NETWORK network"
          reth init \
            --chain /node/$NETWORK.json \
            --datadir /execution \
            --log.file.directory /execution/log
        else
          echo "Execution database for $NETWORK network already exists"
        fi
    container_name: init-execution
    env_file: .env
    volumes:
      - ${DATA_DIR}/execution:/execution:rw
      - ${DATA_DIR}/jwt:/jwt:ro
      - ./shared/${NETWORK}.json:/node/${NETWORK}.json:ro
    depends_on:
      init-consensus:
        condition: service_completed_successfully

  plasma-execution:
    image: ${PLASMA_EXECUTION_IMAGE}:${PLASMA_EXECUTION_TAG}
    user: "1000:1000"
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        reth node \
          --chain /node/$NETWORK.json \
          --datadir /execution \
          --trusted-peers "$(cat /tmp/enodes.txt)" \
          --authrpc.jwtsecret /jwt/jwt.hex \
          --authrpc.addr 0.0.0.0 \
          --authrpc.port 8551 \
          --http \
          --http.addr 0.0.0.0 \
          --http.api eth,net,web3,txpool,debug,admin \
          --http.corsdomain '*' \
          --ws \
          --ws.addr 0.0.0.0 \
          --ws.port 8546 \
          --ws.api eth,net,web3,txpool,debug,admin \
          --ws.corsdomain '*' \
          -vvv \
          --metrics 0.0.0.0:9001 \
          --color never \
          --rpc.gascap "600000000" \
          --rpc.txfeecap "0" \
          --txpool.gas-limit "36000000" \
          --txpool.blobpool-max-count "0" \
          --txpool.blobpool-max-size "0" \
          --txpool.blob-cache-size "0" \
          --log.file.directory /execution/log \
          --prune.accounthistory.distance=10064 \
          --prune.storagehistory.distance=10064 \
          --prune.bodies.distance=10064 \
          --prune.transaction-lookup.full \
          --prune.sender-recovery.full
    container_name: plasma-execution
    env_file: .env
    ports:
      - "8545:8545"   # HTTP RPC
      - "8546:8546"   # WebSocket
      - "9001:9001"   # metrics
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 6<> /dev/tcp/localhost/8545 && exec 6<> /dev/tcp/localhost/8551"]
      interval: 10s
      timeout: 10s
      retries: 30
    volumes:
      - ${DATA_DIR}/execution:/execution:rw
      - ${DATA_DIR}/jwt:/jwt:ro
      - ./enodes.txt:/tmp/enodes.txt:ro
      - ./shared/${NETWORK}.json:/node/${NETWORK}.json:ro
    depends_on:
      init-execution:
        condition: service_completed_successfully
    networks:
      - plasma

  plasma-consensus:
    image: ${PLASMA_CONSENSUS_IMAGE}:${PLASMA_CONSENSUS_TAG}
    user: "1000:1000"
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        plasma-cli observer \
          --config-path /tmp/non-validator.toml \
          --no-color \
          --timeout-stream-manager 10ms \
          --telemetry.enable-metrics \
          --telemetry.enable-health \
          --telemetry.host 0.0.0.0 \
          --telemetry.port 9001 \
          -vvv
    container_name: plasma-consensus
    env_file: .env
    volumes:
      - ${DATA_DIR}/consensus:/consensus:rw
      - ./non-validator.toml:/tmp/non-validator.toml:ro
      - ${DATA_DIR}/jwt:/jwt:ro
      - ./shared/identities:/node/identities:ro
      - ./shared/keys:/node/keys:ro
      - ./shared/${NETWORK}.json:/node/${NETWORK}.json:ro
    depends_on:
      init-consensus:
        condition: service_completed_successfully
      plasma-execution:
        condition: service_healthy
    networks:
      - plasma

networks:
  plasma:
    driver: bridge
